### ISSUE TITLE
No go.mod file. Docker documentation.

### ISSUE THREAD

**Issue by roberthenzel** [alexellis/href-counter#2]
This repository is used in official docker documentation as an example for multi-stage builds:
https://docs.docker.com/build/building/multi-stage/#use-multi-stage-builds
But the mentioned example won't work because this repository lack go.mod file which contains specified go version and dependencies.
![image](https://user-images.githubusercontent.com/15844093/215086183-bd54024a-02b4-4ff1-876a-04676634f2de.png)

**Comment by alexellis** [comment]
Hi @roberthenzel this example predates Go modules, simply write GOMODULE111=off

My blog post was written in 2017 and used Go 1.7, way before modules were available: https://blog.alexellis.io/mutli-stage-docker-builds/

The example will need more than just a go.mod adding to it, I will have a look into separately.

Thanks for stopping by

Alex
